### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by TroyDota** [SevenTV/Server#1]
I really like your project and I would actually like to help a lot. 
I am kinda bored and this is my portfolio https://komodohype.dev
I can also help grow it with streamers I frequently talk to and work for.
```Troy#0003``` on discord if u wanna go ppOverheat

**Comment by AnatoleAM** [comment]
We have a public discord up if you want to discuss contributing @ https://discord.gg/WyqtzzrU9t FeelsOkayMan
